service: office-supplies-cmd

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}

functions:
  app:
    handler: handler.app
    events:
      - http:
          method: post
          path: /slack/events
